version: 1.0.0.{build}
image: Visual Studio 2022
environment:
  matrix:
  - job_name: Windows build
    appveyor_build_worker_image: Visual Studio 2022

  - job_name: MacOS build
    appveyor_build_worker_image: macOS

  - job_name: Linux build
    appveyor_build_worker_image: Ubuntu2204
matrix:
  fast_finish: true

branches:
  only:
  - stable
  - main
skip_tags: true

configuration: Release
platform: x64
shallow_clone: true
dotnet_csproj:
  patch: true
  file: Mirivoice.Desktop\Mirivoice.Desktop.csproj
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'


nuget:
  project_feed: true

for:
  - 
    matrix:
      only:
      - job_name: Linux build

    build_script:
      - pwd
      - dotnet restore Mirivoice.Desktop/Mirivoice.Desktop.csproj
      - dotnet publish Mirivoice.Desktop/Mirivoice.Desktop.csproj -c Release -r linux-x64 --self-contained true
      - cd Mirivoice.Desktop/bin/x64/Release/net8.0/linux-x64/publish/
      - tar -czvf MiriVoice-linux-x64.tar.gz *

  - 
    matrix:
      only:
      - job_name: MacOS build

    build_script:
      - pwd
      - dotnet restore Mirivoice.Desktop/Mirivoice.Desktop.csproj
      - dotnet publish Mirivoice.Desktop/Mirivoice.Desktop.csproj -c Release -r osx-x64 --self-contained true
      - mkdir -p Mirivoice.Desktop/bin/x64/Release/net8.0/osx-x64/MiriVoice.app/Contents/Resources/
      - mkdir -p Mirivoice.Desktop/bin/x64/Release/net8.0/osx-x64/MiriVoice.app/Contents/MacOS/
      - cp -R Mirivoice.Desktop/bin/x64/Release/net8.0/osx-x64/publish/* Mirivoice.Desktop/bin/x64/Release/net8.0/osx-x64/MiriVoice.app/Contents/MacOS/
      - cp Mirivoice/Assets/mirivoice.icns Mirivoice.Desktop/bin/x64/Release/net8.0/osx-x64/MiriVoice.app/Contents/Resources/
      - cp Mirivoice/Assets/Info.plist Mirivoice.Desktop/bin/x64/Release/net8.0/osx-x64/MiriVoice.app/Contents/
      - npm install -g create-dmg
      - codesign --force --deep --verbose --sign "Developer ID Application: EX3exp" Mirivoice.Desktop/bin/x64/Release/net8.0/osx-x64/MiriVoice.app
      - create-dmg Mirivoice.Desktop/bin/x64/Release/net8.0/osx-x64/MiriVoice.app
      - mv *.dmg MiriVoice-osx-x64.dmg
  - 
    matrix:
      only:
      - job_name: Windows build

    build_script:
      - pwd
      - dotnet restore Mirivoice.Desktop/Mirivoice.Desktop.csproj
      - dotnet publish Mirivoice.Desktop/Mirivoice.Desktop.csproj -c Release -r win-x64 --self-contained true

  
  


artifacts:
- path: Mirivoice.Desktop\bin\x64\Release\net8.0\win-x64\publish\
  name: MiriVoice-win-x64
- path: MiriVoice-osx-x64.dmg
- path: Mirivoice.Desktop\bin\x64\Release\net8.0\linux-x64\publish\MiriVoice-linux-x64.tar.gz
deploy:
- provider: GitHub
  tag: build/$(APPVEYOR_BUILD_VERSION)
  release: MiriVoice-v$(APPVEYOR_BUILD_VERSION) Beta
  description: $(APPVEYOR_BUILD_VERSION) Beta ($(APPVEYOR_REPO_COMMIT_TIMESTAMP))
  auth_token:
    secure: EZGpxMjy4Z14QdM0UqgRTRn+GRbehi7bp6TtZVjH04PqNqMljX9d1QU29YDHOhld
  repository: EX3exp/MiriVoice
  prerelease: true
  force_update: true
  on:
    branch: main
- provider: GitHub
  tag: build/$(APPVEYOR_BUILD_VERSION)
  release: MiriVoice-v$(APPVEYOR_BUILD_VERSION)
  description: $(APPVEYOR_BUILD_VERSION) ($(APPVEYOR_REPO_COMMIT_TIMESTAMP))
  auth_token:
    secure: EZGpxMjy4Z14QdM0UqgRTRn+GRbehi7bp6TtZVjH04PqNqMljX9d1QU29YDHOhld
  repository: EX3exp/MiriVoice
  prerelease: false
  force_update: true
  on:
    branch: stable