version: 1.0.0.{build}
branches:
  only:
  - stable
  - main
skip_tags: true
image:
- Visual Studio 2022
- macOS
- Ubuntu2204
configuration: Release
platform: Any CPU
shallow_clone: true
dotnet_csproj:
  patch: true
  file: Mirivoice.Desktop\Mirivoice.Desktop.csproj
  version: '{version}'
  version_prefix: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
nuget:
  project_feed: true
build_script:
- cmd: dotnet publish -c Release -r %PLATFORM% --self-contained
artifacts:
- path: bin\Release\net8.0\win-x64\MiriVoice.zip
  name: MiriVoice-win-x64
- path: bin\Release\net8.0\osx-x64\MiriVoice.zip
  name: MiriVoice-macOS
- path: bin\Release\net8.0\linux-x64\MiriVoice.zip
  name: MiriVoice-linux
deploy:
- provider: GitHub
  tag: build/$(APPVEYOR_BUILD_VERSION)
  release: MiriVoice-v$(APPVEYOR_BUILD_VERSION) Beta
  description: $(APPVEYOR_BUILD_VERSION) Beta ($(APPVEYOR_REPO_COMMIT_TIMESTAMP))
  auth_token:
    secure: EZGpxMjy4Z14QdM0UqgRTRn+GRbehi7bp6TtZVjH04PqNqMljX9d1QU29YDHOhld
  repository: EX3exp/MiriVoice
  prerelease: true
  force_update: true
  on:
    branch: main
- provider: GitHub
  tag: build/$(APPVEYOR_BUILD_VERSION)
  release: MiriVoice-v$(APPVEYOR_BUILD_VERSION)
  description: $(APPVEYOR_BUILD_VERSION) ($(APPVEYOR_REPO_COMMIT_TIMESTAMP))
  auth_token:
    secure: EZGpxMjy4Z14QdM0UqgRTRn+GRbehi7bp6TtZVjH04PqNqMljX9d1QU29YDHOhld
  repository: EX3exp/MiriVoice
  prerelease: false
  force_update: true
  on:
    branch: stable