name: Build and Deploy

on:
  push:
    branches:
      - stable
      #- main

jobs:
  build:
    name: Build Project
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        dotnet-version: ['8.x']

    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      VERSION: 1.0.0.0  # Set the version number here

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Save version to GITHUB_ENV
        run: echo "VERSION=${{ env.VERSION }}" >> $GITHUB_ENV

      - name: Restore dependencies
        run: nuget restore

      - name: Build and make appcast (Windows only)
        if: matrix.os == 'windows-latest'
        run: python Mirivoice.Desktop/appveyor.py 2>&1

      - name: Build and make appcast (Linux/Mac)
        if: matrix.os != 'windows-latest'
        run: python3 Mirivoice.Desktop/appveyor.py 2>&1

      - name: Package win-x86 artifact
        if: matrix.os == 'windows-latest'
        run: Compress-Archive -Path Mirivoice.Desktop/bin/win-x86/* -DestinationPath MiriVoice-win-x86.zip

      - name: Package win-x64 artifact
        if: matrix.os == 'windows-latest'
        run: Compress-Archive -Path Mirivoice.Desktop/bin/win-x64/* -DestinationPath MiriVoice-win-x64.zip

      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: MiriVoice
          path: |
            Mirivoice.Desktop/bin/win-x86/MiriVoice-win-x86.zip
            Mirivoice.Desktop/bin/win-x64/MiriVoice-win-x64.zip
            Mirivoice.Desktop/osxbuild/MiriVoice-osx-x64.zip
            MiriVoice-linux-x64.tar.gz
            appcast.win-x86.xml
            appcast.win-x64.xml
            appcast.linux-x64.xml
            appcast.osx-x64.xml

  deploy:
    name: Deploy to GitHub Releases
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create GitHub release for main branch
        if: github.ref == 'refs/heads/main'
        id: create_release_beta
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build/${{ env.VERSION }}  
          name: MiriVoice v${{ env.VERSION }} Beta
          draft: false
          generate_release_notes: true
          prerelease: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create GitHub release for stable branch
        if: github.ref == 'refs/heads/stable'
        id: create_release_stable
        uses: softprops/action-gh-release@v1
        with:
          tag_name: build/${{ env.VERSION }}  
          name: MiriVoice v${{ env.VERSION }}
          generate_release_notes: true
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release_beta.outputs.upload_url || steps.create_release_stable.outputs.upload_url }}
          asset_path: |
            Mirivoice.Desktop/bin/win-x86/MiriVoice-win-x86.zip
            Mirivoice.Desktop/bin/win-x64/MiriVoice-win-x64.zip
            Mirivoice.Desktop/osxbuild/MiriVoice-osx-x64.zip
            MiriVoice-linux-x64.tar.gz
            appcast.win-x86.xml
            appcast.win-x64.xml
            appcast.linux-x64.xml
            appcast.osx-x64.xml
