name: Deploy Release (Windows)

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

jobs:
  build:
    env:
      DOTNET_NOLOGO: true
      DOTNET_CLI_TELEMETRY_OPTOUT: 1
      VERSION: ${{ github.ref_name }}

    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Check version
        run: |
          $TAG = "${{ github.ref_name }}"
          echo $TAG

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: nuget restore

      - name: Build and make appcast (Windows only)
        run: python Mirivoice.Desktop/appveyor.py 2>&1

      - name: Zip
        run: |
          $VERSION="${{ github.ref_name }}"
          echo $VERSION
          Compress-Archive -Path Mirivoice.Desktop/bin/win-x86/* -DestinationPath ./MiriVoice-win-x86.zip
          Compress-Archive -Path Mirivoice.Desktop/bin/win-x64/* -DestinationPath ./MiriVoice-win-x64.zip

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: |
            MiriVoice-win-x86.zip
            MiriVoice-win-x64.zip
            appcast.win-x86.xml
            appcast.win-x64.xml
